package com.mallgo.model;

import java.util.Date;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.shop_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Float lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.city
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.state
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.country
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.detail
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.zip
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.phone_number
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.reciver_name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String reciverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.id
     *
     * @return the value of ADDRESS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.id
     *
     * @param id the value for ADDRESS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.user_id
     *
     * @return the value of ADDRESS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.user_id
     *
     * @param userId the value for ADDRESS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.shop_id
     *
     * @return the value of ADDRESS.shop_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.shop_id
     *
     * @param shopId the value for ADDRESS.shop_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.lon
     *
     * @return the value of ADDRESS.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Float getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.lon
     *
     * @param lon the value for ADDRESS.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setLon(Float lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.lat
     *
     * @return the value of ADDRESS.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.lat
     *
     * @param lat the value for ADDRESS.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.city
     *
     * @return the value of ADDRESS.city
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.city
     *
     * @param city the value for ADDRESS.city
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCity(Long city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.state
     *
     * @return the value of ADDRESS.state
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.state
     *
     * @param state the value for ADDRESS.state
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.country
     *
     * @return the value of ADDRESS.country
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.country
     *
     * @param country the value for ADDRESS.country
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCountry(Long country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.detail
     *
     * @return the value of ADDRESS.detail
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.detail
     *
     * @param detail the value for ADDRESS.detail
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.zip
     *
     * @return the value of ADDRESS.zip
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.zip
     *
     * @param zip the value for ADDRESS.zip
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.phone_number
     *
     * @return the value of ADDRESS.phone_number
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.phone_number
     *
     * @param phoneNumber the value for ADDRESS.phone_number
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.reciver_name
     *
     * @return the value of ADDRESS.reciver_name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getReciverName() {
        return reciverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.reciver_name
     *
     * @param reciverName the value for ADDRESS.reciver_name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setReciverName(String reciverName) {
        this.reciverName = reciverName == null ? null : reciverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.created_by
     *
     * @return the value of ADDRESS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.created_by
     *
     * @param createdBy the value for ADDRESS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.modified_by
     *
     * @return the value of ADDRESS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.modified_by
     *
     * @param modifiedBy the value for ADDRESS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.created_ts
     *
     * @return the value of ADDRESS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.created_ts
     *
     * @param createdTs the value for ADDRESS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.modified_ts
     *
     * @return the value of ADDRESS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.modified_ts
     *
     * @param modifiedTs the value for ADDRESS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}