package com.mallgo.model;

import java.util.Date;

public class DomainValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.domain_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.low_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long lowValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.hight_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long hightValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.alias
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.sort_order
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.is_active
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAIN_VALUE.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.id
     *
     * @return the value of DOMAIN_VALUE.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.id
     *
     * @param id the value for DOMAIN_VALUE.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.domain_id
     *
     * @return the value of DOMAIN_VALUE.domain_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.domain_id
     *
     * @param domainId the value for DOMAIN_VALUE.domain_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.low_value
     *
     * @return the value of DOMAIN_VALUE.low_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getLowValue() {
        return lowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.low_value
     *
     * @param lowValue the value for DOMAIN_VALUE.low_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setLowValue(Long lowValue) {
        this.lowValue = lowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.hight_value
     *
     * @return the value of DOMAIN_VALUE.hight_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getHightValue() {
        return hightValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.hight_value
     *
     * @param hightValue the value for DOMAIN_VALUE.hight_value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setHightValue(Long hightValue) {
        this.hightValue = hightValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.value
     *
     * @return the value of DOMAIN_VALUE.value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.value
     *
     * @param value the value for DOMAIN_VALUE.value
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.alias
     *
     * @return the value of DOMAIN_VALUE.alias
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.alias
     *
     * @param alias the value for DOMAIN_VALUE.alias
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.sort_order
     *
     * @return the value of DOMAIN_VALUE.sort_order
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.sort_order
     *
     * @param sortOrder the value for DOMAIN_VALUE.sort_order
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.is_active
     *
     * @return the value of DOMAIN_VALUE.is_active
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.is_active
     *
     * @param isActive the value for DOMAIN_VALUE.is_active
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.created_by
     *
     * @return the value of DOMAIN_VALUE.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.created_by
     *
     * @param createdBy the value for DOMAIN_VALUE.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.modified_by
     *
     * @return the value of DOMAIN_VALUE.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.modified_by
     *
     * @param modifiedBy the value for DOMAIN_VALUE.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.created_ts
     *
     * @return the value of DOMAIN_VALUE.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.created_ts
     *
     * @param createdTs the value for DOMAIN_VALUE.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAIN_VALUE.modified_ts
     *
     * @return the value of DOMAIN_VALUE.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAIN_VALUE.modified_ts
     *
     * @param modifiedTs the value for DOMAIN_VALUE.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}