package com.mallgo.model;

import java.math.BigDecimal;
import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.product_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.list_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private BigDecimal listPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.origin_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private BigDecimal originPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.in_stock_quantity
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Integer inStockQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.attribute1
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.attribute2
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.attribute3
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.attribute4
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.attribute5
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.id
     *
     * @return the value of ITEM.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.id
     *
     * @param id the value for ITEM.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.product_id
     *
     * @return the value of ITEM.product_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.product_id
     *
     * @param productId the value for ITEM.product_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.list_price
     *
     * @return the value of ITEM.list_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public BigDecimal getListPrice() {
        return listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.list_price
     *
     * @param listPrice the value for ITEM.list_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.origin_price
     *
     * @return the value of ITEM.origin_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public BigDecimal getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.origin_price
     *
     * @param originPrice the value for ITEM.origin_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.status
     *
     * @return the value of ITEM.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.status
     *
     * @param status the value for ITEM.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.in_stock_quantity
     *
     * @return the value of ITEM.in_stock_quantity
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Integer getInStockQuantity() {
        return inStockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.in_stock_quantity
     *
     * @param inStockQuantity the value for ITEM.in_stock_quantity
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setInStockQuantity(Integer inStockQuantity) {
        this.inStockQuantity = inStockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.attribute1
     *
     * @return the value of ITEM.attribute1
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.attribute1
     *
     * @param attribute1 the value for ITEM.attribute1
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.attribute2
     *
     * @return the value of ITEM.attribute2
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.attribute2
     *
     * @param attribute2 the value for ITEM.attribute2
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.attribute3
     *
     * @return the value of ITEM.attribute3
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.attribute3
     *
     * @param attribute3 the value for ITEM.attribute3
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.attribute4
     *
     * @return the value of ITEM.attribute4
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.attribute4
     *
     * @param attribute4 the value for ITEM.attribute4
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.attribute5
     *
     * @return the value of ITEM.attribute5
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.attribute5
     *
     * @param attribute5 the value for ITEM.attribute5
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.created_by
     *
     * @return the value of ITEM.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.created_by
     *
     * @param createdBy the value for ITEM.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.modified_by
     *
     * @return the value of ITEM.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.modified_by
     *
     * @param modifiedBy the value for ITEM.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.created_ts
     *
     * @return the value of ITEM.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.created_ts
     *
     * @param createdTs the value for ITEM.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.modified_ts
     *
     * @return the value of ITEM.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.modified_ts
     *
     * @param modifiedTs the value for ITEM.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}