package com.mallgo.model;

import java.util.Date;

public class OrderAuditLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.order_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.action_type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.action_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date actionTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.comment
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.modifier
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_AUDIT_LOG.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.id
     *
     * @return the value of ORDER_AUDIT_LOG.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.id
     *
     * @param id the value for ORDER_AUDIT_LOG.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.order_id
     *
     * @return the value of ORDER_AUDIT_LOG.order_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.order_id
     *
     * @param orderId the value for ORDER_AUDIT_LOG.order_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.action_type
     *
     * @return the value of ORDER_AUDIT_LOG.action_type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.action_type
     *
     * @param actionType the value for ORDER_AUDIT_LOG.action_type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setActionType(Long actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.action_ts
     *
     * @return the value of ORDER_AUDIT_LOG.action_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getActionTs() {
        return actionTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.action_ts
     *
     * @param actionTs the value for ORDER_AUDIT_LOG.action_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setActionTs(Date actionTs) {
        this.actionTs = actionTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.comment
     *
     * @return the value of ORDER_AUDIT_LOG.comment
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.comment
     *
     * @param comment the value for ORDER_AUDIT_LOG.comment
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.modifier
     *
     * @return the value of ORDER_AUDIT_LOG.modifier
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.modifier
     *
     * @param modifier the value for ORDER_AUDIT_LOG.modifier
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.created_by
     *
     * @return the value of ORDER_AUDIT_LOG.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.created_by
     *
     * @param createdBy the value for ORDER_AUDIT_LOG.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.modified_by
     *
     * @return the value of ORDER_AUDIT_LOG.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.modified_by
     *
     * @param modifiedBy the value for ORDER_AUDIT_LOG.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.created_ts
     *
     * @return the value of ORDER_AUDIT_LOG.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.created_ts
     *
     * @param createdTs the value for ORDER_AUDIT_LOG.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_AUDIT_LOG.modified_ts
     *
     * @return the value of ORDER_AUDIT_LOG.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_AUDIT_LOG.modified_ts
     *
     * @param modifiedTs the value for ORDER_AUDIT_LOG.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}