package com.mallgo.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ship_address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long shipAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.courier_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long courierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.payment_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.total_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.order_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date orderTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.code
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.id
     *
     * @return the value of ORDERS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.id
     *
     * @param id the value for ORDERS.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.user_id
     *
     * @return the value of ORDERS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.user_id
     *
     * @param userId the value for ORDERS.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ship_address_id
     *
     * @return the value of ORDERS.ship_address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getShipAddressId() {
        return shipAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ship_address_id
     *
     * @param shipAddressId the value for ORDERS.ship_address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setShipAddressId(Long shipAddressId) {
        this.shipAddressId = shipAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.courier_id
     *
     * @return the value of ORDERS.courier_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getCourierId() {
        return courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.courier_id
     *
     * @param courierId the value for ORDERS.courier_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCourierId(Long courierId) {
        this.courierId = courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.payment_id
     *
     * @return the value of ORDERS.payment_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.payment_id
     *
     * @param paymentId the value for ORDERS.payment_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.total_price
     *
     * @return the value of ORDERS.total_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.total_price
     *
     * @param totalPrice the value for ORDERS.total_price
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.order_ts
     *
     * @return the value of ORDERS.order_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getOrderTs() {
        return orderTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.order_ts
     *
     * @param orderTs the value for ORDERS.order_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setOrderTs(Date orderTs) {
        this.orderTs = orderTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.status
     *
     * @return the value of ORDERS.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.status
     *
     * @param status the value for ORDERS.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.type
     *
     * @return the value of ORDERS.type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.type
     *
     * @param type the value for ORDERS.type
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.code
     *
     * @return the value of ORDERS.code
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.code
     *
     * @param code the value for ORDERS.code
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.created_by
     *
     * @return the value of ORDERS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.created_by
     *
     * @param createdBy the value for ORDERS.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.modified_by
     *
     * @return the value of ORDERS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.modified_by
     *
     * @param modifiedBy the value for ORDERS.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.created_ts
     *
     * @return the value of ORDERS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.created_ts
     *
     * @param createdTs the value for ORDERS.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.modified_ts
     *
     * @return the value of ORDERS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.modified_ts
     *
     * @param modifiedTs the value for ORDERS.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}