package com.mallgo.model;

import java.util.Date;

public class ShopPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.shop_id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.pic_name
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.created_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.modified_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.created_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_PIC.modified_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.id
     *
     * @return the value of SHOP_PIC.id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.id
     *
     * @param id the value for SHOP_PIC.id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.shop_id
     *
     * @return the value of SHOP_PIC.shop_id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.shop_id
     *
     * @param shopId the value for SHOP_PIC.shop_id
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.pic_name
     *
     * @return the value of SHOP_PIC.pic_name
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.pic_name
     *
     * @param picName the value for SHOP_PIC.pic_name
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.created_by
     *
     * @return the value of SHOP_PIC.created_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.created_by
     *
     * @param createdBy the value for SHOP_PIC.created_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.modified_by
     *
     * @return the value of SHOP_PIC.modified_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.modified_by
     *
     * @param modifiedBy the value for SHOP_PIC.modified_by
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.created_ts
     *
     * @return the value of SHOP_PIC.created_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.created_ts
     *
     * @param createdTs the value for SHOP_PIC.created_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_PIC.modified_ts
     *
     * @return the value of SHOP_PIC.modified_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_PIC.modified_ts
     *
     * @param modifiedTs the value for SHOP_PIC.modified_ts
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}