package com.mallgo.model;

import java.util.Date;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Float lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date createdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    private Date modifiedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.id
     *
     * @return the value of SHOP.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.id
     *
     * @param id the value for SHOP.id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.user_id
     *
     * @return the value of SHOP.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.user_id
     *
     * @param userId the value for SHOP.user_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.address_id
     *
     * @return the value of SHOP.address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.address_id
     *
     * @param addressId the value for SHOP.address_id
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.lon
     *
     * @return the value of SHOP.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Float getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.lon
     *
     * @param lon the value for SHOP.lon
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setLon(Float lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.lat
     *
     * @return the value of SHOP.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.lat
     *
     * @param lat the value for SHOP.lat
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.name
     *
     * @return the value of SHOP.name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.name
     *
     * @param name the value for SHOP.name
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.status
     *
     * @return the value of SHOP.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.status
     *
     * @param status the value for SHOP.status
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.created_by
     *
     * @return the value of SHOP.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.created_by
     *
     * @param createdBy the value for SHOP.created_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.modified_by
     *
     * @return the value of SHOP.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.modified_by
     *
     * @param modifiedBy the value for SHOP.modified_by
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.created_ts
     *
     * @return the value of SHOP.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.created_ts
     *
     * @param createdTs the value for SHOP.created_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.modified_ts
     *
     * @return the value of SHOP.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public Date getModifiedTs() {
        return modifiedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.modified_ts
     *
     * @param modifiedTs the value for SHOP.modified_ts
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }
}