ALTER TABLE SHOP CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE SHOP CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ADDRESS CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE ADDRESS CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CART CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE CART CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CART_ITEM CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE CART_ITEM CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CATEGORY CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE CATEGORY CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE COMMENT CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE COMMENT CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE COURIER CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE COURIER CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE DOMAIN CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE DOMAIN CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE DOMAIN_VALUE CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE DOMAIN_VALUE CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ITEM CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE ITEM CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE LINE_ITEM CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE LINE_ITEM CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ORDER_AUDIT_LOG CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE ORDER_AUDIT_LOG CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ORDERS CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE ORDERS CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE PAYMENT CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE PAYMENT CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE PRODUCT CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE PRODUCT CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE RECOMMENDATION CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE RECOMMENDATION CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE SHOP CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE SHOP CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TAG CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE TAG CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE USER CHANGE COLUMN MODIFIED_TS MODIFIED_TS TIMESTAMP NULL;
ALTER TABLE USER CHANGE COLUMN CREATED_TS CREATED_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ORDER_AUDIT_LOG CHANGE COLUMN `action_ts` `action_ts` TIMESTAMP NOT NULL;

ALTER TABLE ORDERS CHANGE COLUMN `order_ts` `order_ts` TIMESTAMP NOT NULL;