package com.mallgo.persistence;

import com.mallgo.model.Courier;
import com.mallgo.model.CourierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<Courier> selectByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    Courier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") Courier record, @Param("example") CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") Courier record, @Param("example") CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURIER
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(Courier record);
}