package com.mallgo.persistence;

import com.mallgo.model.DomainValue;
import com.mallgo.model.DomainValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(DomainValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(DomainValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(DomainValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(DomainValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<DomainValue> selectByExample(DomainValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    DomainValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") DomainValue record, @Param("example") DomainValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") DomainValue record, @Param("example") DomainValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(DomainValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN_VALUE
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(DomainValue record);
}