package com.mallgo.persistence;

import com.mallgo.model.Domain;
import com.mallgo.model.DomainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<Domain> selectByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    Domain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOMAIN
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(Domain record);
}