package com.mallgo.persistence;

import com.mallgo.model.LineItem;
import com.mallgo.model.LineItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LineItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(LineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(LineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<LineItem> selectByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    LineItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") LineItem record, @Param("example") LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") LineItem record, @Param("example") LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(LineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINE_ITEM
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(LineItem record);
}