package com.mallgo.persistence;

import com.mallgo.model.OrderAuditLog;
import com.mallgo.model.OrderAuditLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderAuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(OrderAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(OrderAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<OrderAuditLog> selectByExample(OrderAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    OrderAuditLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") OrderAuditLog record, @Param("example") OrderAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") OrderAuditLog record, @Param("example") OrderAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(OrderAuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_AUDIT_LOG
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(OrderAuditLog record);
}