package com.mallgo.persistence;

import com.mallgo.model.Recommendation;
import com.mallgo.model.RecommendationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecommendationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int countByExample(RecommendationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByExample(RecommendationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insert(Recommendation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int insertSelective(Recommendation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    List<Recommendation> selectByExample(RecommendationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    Recommendation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") Recommendation record, @Param("example") RecommendationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByExample(@Param("record") Recommendation record, @Param("example") RecommendationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKeySelective(Recommendation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECOMMENDATION
     *
     * @mbggenerated Thu May 15 18:43:20 CST 2014
     */
    int updateByPrimaryKey(Recommendation record);
}