package com.mallgo.persistence;

import com.mallgo.model.ShopPic;
import com.mallgo.model.ShopPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int countByExample(ShopPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int deleteByExample(ShopPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int insert(ShopPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int insertSelective(ShopPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    List<ShopPic> selectByExample(ShopPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    ShopPic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int updateByExampleSelective(@Param("record") ShopPic record, @Param("example") ShopPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int updateByExample(@Param("record") ShopPic record, @Param("example") ShopPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int updateByPrimaryKeySelective(ShopPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOP_PIC
     *
     * @mbggenerated Fri May 16 22:49:50 CST 2014
     */
    int updateByPrimaryKey(ShopPic record);
}